In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr1[3]

4

In [5]:
arr1[2:4]

array([3, 4])

In [8]:
arr1[-1]

5

In [10]:
arr2=np.arange(24)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [11]:
arr2=np.arange(24).reshape(6,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
arr2[2]

array([ 8,  9, 10, 11])

In [13]:
arr2[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
arr2[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [15]:
arr2[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [16]:
for i in arr2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [17]:
for i in np.nditer(arr2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
