In [1]:
import numpy as np

In [2]:
arr=np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr

array([[46, 43, 77, 12, 60],
       [70, 86, 76, 16, 87],
       [63, 22, 96, 44, 85],
       [28, 53, 31, 67, 65]])

In [3]:
arr[0][4]

60

In [4]:
arr>50

array([[False, False,  True, False,  True],
       [ True,  True,  True, False,  True],
       [ True, False,  True, False,  True],
       [False,  True, False,  True,  True]])

In [5]:
arr[arr>50]

array([77, 60, 70, 86, 76, 87, 63, 96, 85, 53, 67, 65])

In [6]:
arr[(arr>50) & (arr%2!=0)]
arr

array([[46, 43, 77, 12, 60],
       [70, 86, 76, 16, 87],
       [63, 22, 96, 44, 85],
       [28, 53, 31, 67, 65]])

In [9]:
arr[(arr>50) & (arr%2!=0)]=0
arr

array([[46, 43,  0, 12, 60],
       [70, 86, 76, 16,  0],
       [ 0, 22, 96, 44,  0],
       [28,  0, 31,  0,  0]])