In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr1.shape

(5,)

In [5]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2.shape

(2, 3)

In [7]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [8]:
arr3.shape

(2, 2, 3)

In [9]:
arr3.ndim

3

In [11]:
arr3.size

12

In [13]:
arr3.itemsize

4

In [14]:
arr3.dtype

dtype('int32')

In [15]:
arr3.astype('float')

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

In [17]:
arr3.astype('str')

array([[['1', '2', '3'],
        ['4', '5', '6']],

       [['7', '8', '9'],
        ['10', '11', '12']]], dtype='<U11')