In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])


In [3]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [4]:
arr1+arr2

array([ 5,  7,  9, 11, 13, 15])

In [6]:
print(arr1*2)

[ 2  4  6  8 10 12]


In [7]:
arr1>2

array([False, False,  True,  True,  True,  True])

In [8]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [9]:
arr3=np.array([1,2,3,4,5,6]).reshape(2,3)
arr4=np.array([4,5,6,7,8,9]).reshape(3,2)


In [11]:
arr3


array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr4

array([[4, 5],
       [6, 7],
       [8, 9]])

In [13]:
arr3.dot(arr4)

array([[ 40,  46],
       [ 94, 109]])

In [15]:

arr3.max()

6

In [16]:
arr3.min()

1

In [17]:
arr3.max(axis=0)

array([4, 5, 6])

In [18]:
arr3.min(axis=1)

array([1, 4])

In [19]:
arr3.sum()

21

In [20]:
arr3.sum(axis=0)

array([5, 7, 9])

In [21]:
arr3.mean()

3.5

In [22]:
arr3.mean(axis=0)

array([2.5, 3.5, 4.5])

In [23]:
arr3.std()

1.707825127659933

In [24]:
np.sin(arr3)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [25]:
np.median(arr3)

3.5

In [26]:
np.exp(arr3)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])