In [1]:
import numpy as np

In [2]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
arr1.ravel()

array([1, 2, 3, 4, 5, 6])

In [4]:
arr2=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
arr2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr1.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr3=np.array([[7,8,9],[10,11,12]])
arr3

array([[ 7,  8,  9],
       [10, 11, 12]])

In [13]:
np.hstack((arr1,arr3))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [14]:
np.vstack((arr1,arr3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
np.hsplit(arr1,3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [18]:
np.vsplit(arr1,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]